### ISSUE TITLE
Check for array as a return of the loader

### ISSUE THREAD

**Issue by audiBookning** [TreeMan360/nestjs-graphql-dataloader#1]
When the loader does not return an array, graphql return this  error:

> "..."message": "docs.forEach is not a function",..."

It is not the fault of this package, but it is nonetheless ugly for the end user.

I would suggest to add a simple check in the ensureOrder function to avoid it and throw an exception instead. 

Edit: Or maybe not? NestJs should be the one to intercept those kind of errors and format them before reaching the user?
On second though i will close this issue.

Thanks for this package. It is very interesting and useful.

**Comment by TreeMan360** [comment]
Hey, you should *always* return an array from your DataLoader. Does that make sense?

**Comment by TreeMan360** [comment]
I will update the documentation later to reflect this and make this more obvious without having to read the underlying dataloader documentation.

**Comment by audiBookning** [comment]
> Hey, you should _always_ return an array from your DataLoader. Does that make sense?

Yes totally.
And i only saw this error because when i made the test with this library, i didn't use a database in the loader. I used another api that unfortunately did not give an empty array when there is no results to return. 

Like you said, i am not familiar with DataLoader, but this situation was because, at the time it was very late, the level of tiredness was kind of high and i must confess that i wasted more time to debug this simple situation than time i had to give it.

Thanks nonetheless and i will add that a more complete docs are always welcome.
