### ISSUE TITLE
Nest could not find TestLoader element (this provider does not exist in the current context)

### ISSUE THREAD

**Issue by jonathborg** [TreeMan360/nestjs-graphql-dataloader#14]
What about this error? I'm not asking for a fix. But, do you know what means?
I followed the steps, one by one. I tryed to put the interceptor inside local module and app.module.
The error show up only when I implement 2 dataloaders. It works nice with one dataloader.

NestJS Version: ^7.4.2

**Comment by longtomjr** [comment]
Same issue here, followed the steps from the readme as well.

This seems like a know issue, and the fix is to make the loader request scoped: https://github.com/TreeMan360/nestjs-graphql-dataloader/issues/9#issuecomment-651707054

For more info see #12 as well

**Comment by TreeMan360** [comment]
Hey, sorry for not updating this issue. I am using this in production and I do not have this problem which is strange.

I will look at this in the next few days and I will let you know my findings and create a hot-fix.

Sorry for the delay on this I am just very snowed under work wise at the moment.

**Comment by jonathborg** [comment]
@Injectable({ scope: Scope.REQUEST }) makes difference for me in recent versions of nest. I think this is required.

You just need to accept this PR: https://github.com/TreeMan360/nestjs-graphql-dataloader/pull/12
