### ISSUE TITLE
Is dataloader configurable?

### ISSUE THREAD

**Issue by zekenie** [TreeMan360/nestjs-graphql-dataloader#4]
Hi!

Playing around with this package. I'm enjoying it a lot so far!

I was wondering, is it possible for you to expose DataLoader's configuration. I want to look into [scheduling](https://github.com/graphql/dataloader#batch-scheduling) and it doesn't seem like this is currently possible.

Thanks!

**Comment by TreeMan360** [comment]
Thanks! Sure, no problem, I can do this for you. I am however very busy for the next week with a product launch. Happy to accept a PR if you can't wait.

**Comment by zekenie** [comment]
@TreeMan360 Any hottakes on how you'd want it done in your library? I'd be happy to implement? Maybe define a method on each loader class that returns the configuration?

**Comment by zekenie** [comment]
Good luck with the launch!

**Comment by TreeMan360** [comment]
> @TreeMan360 Any hottakes on how you'd want it done in your library? I'd be happy to implement? Maybe define a method on each loader class that returns the configuration?

Yep, extending ```getOptions``` ```IOrderedNestDataLoaderOptions ```seems like a sensible starting point to me :)

**Comment by TreeMan360** [comment]
Again, thanks for your PR. I have merged and am therefore closing this issue.

**Comment by zekenie** [comment]
@TreeMan360 Awesome! Would you mind publishing to npm? I'd love to use

**Comment by TreeMan360** [comment]
@zekenie done (oops, sorry about that!)

**Comment by zekenie** [comment]
🙏 Thanks!
